name: daily

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  schedule:
    - cron: "20 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CHECKOUT
        uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: SNAKE
        id: snake_svg
        uses: Platane/snk@v2
        # uses: aelassas/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./2023/snake_svg.svg
      - name: PUSH
        uses: EndBug/add-and-commit@v9
        with:

          message: "daily"
          github_token: ${{ secrets.GITHUB_TOKEN }}
